# Generated by Django 5.2.8 on 2025-11-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_options_alter_post_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('PB', 'انتشار'), ('DF', 'پیش نویس'), ('RE', 'رد شده')], default='DF', max_length=100, verbose_name='وضعیت'),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('message', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11)),
                ('subject', models.CharField(choices=[('پیشنهاد', 'پیشنهاد'), ('انتقاد', 'انتقاد'), ('گزارش', 'گزارش مشکل')], max_length=250)),
            ],
            options={
                'verbose_name': 'تیکت',
                'verbose_name_plural': 'تیکت ها',
                'ordering': ['-name'],
                'indexes': [models.Index(fields=['-name'], name='blog_ticket_name_02e7ad_idx')],
            },
        ),
    ]
