# Generated by Django 6.0.1 on 2026-02-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_image_description_image_image_image_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='post_image', verbose_name='تصویر'),
        ),
    ]
