# Generated by Django 6.0.1 on 2026-02-05 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_image_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'تصویر', 'verbose_name_plural': 'تصاویر'},
        ),
        migrations.RemoveIndex(
            model_name='image',
            name='blog_image_title_1c8b55_idx',
        ),
    ]
