# Generated by Django 6.0.1 on 2026-02-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_image_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('-title',), 'verbose_name': 'تصویر', 'verbose_name_plural': 'تصاویر'},
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['-title'], name='blog_image_title_1c8b55_idx'),
        ),
    ]
