# Generated by Django 6.0.1 on 2026-02-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('انتشار', 'انتشار'), ('منتشر نشده', 'پیش نویس'), ('رد شده', 'رد شده')], default='منتشر نشده', max_length=100, verbose_name='وضعیت'),
        ),
    ]
