# Generated by Django 6.0.1 on 2026-02-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('PB', 'انتشار'), ('DF', 'پیش نویس'), ('RE', 'رد شده')], default='DF', max_length=100, verbose_name='وضعیت'),
        ),
    ]
